FROM node:20.18

WORKDIR /usr/src/admin-panel

COPY package*.json ./

COPY ./.next ./.next
COPY ./public ./public

RUN npm install --omit=dev && npm cache clean --force

EXPOSE 3001

CMD [ "npm", "start" ]